### ISSUE TITLE
Branch for Spree 1.3

### ISSUE THREAD

**Issue by isaacfreeman** [joshnuss/spree_stock_notifications#1]
I've modified spree_stock_notifications for a client who's still on Spree 1.3. If you'd like to make a `1-3-stable branch` I can send a pull request.

It includes one functional change, to have separate lists of email addresses for low stock and out-of-stock notifications, although I've kept the default of using the emails for admin users as in the master version.

**Comment by joshnuss** [comment]
@isaacfreeman sounds great! PR is welcome

**Comment by isaacfreeman** [comment]
Cool. I don't want to send the PR to master, though, as it's not relevant to anybody on a recent Spree version. Could I get you to make a 1-3-stable branch first?

**Comment by joshnuss** [comment]
Hey Isaac,

NP, just added a 1-3-stable branch.

On Mon, Mar 2, 2015 at 5:36 PM, Isaac Freeman notifications@github.com
wrote:

> Cool. I don't want to send the PR to master, though, as it's not relevant
> to anybody on a recent Spree version. Could I get you to make a 1-3-stable
> branch first?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshnuss/spree_stock_notifications/issues/1#issuecomment-76842131
> .

## 

Joshua Nussbaum
